server:
  port: 31001
  servlet:
    context-path: /mysql
    application-display-name: mysql1


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ireport?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall,log4j2,config
      max-active: 100
      initial-size: 20
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        allow: 127.0.0.1
        login-username: admin
        login-password: admin

mybatis:
  mapper-locations: classpath:sqlMap/*Mapper.xml

